name: GPKG and ArcGIS Automation

on:
  schedule:
    - cron: '30 4 * * *'   # 10:00 AM IST → update_gpkg_from_drive.py
    - cron: '0 5 * * *'    # 10:30 AM IST → push_to_arcgis.py
    - cron: '30 11 * * *'  # 5:00 PM IST  → update_gpkg_from_drive.py
    - cron: '0 12 * * *'   # 5:30 PM IST  → push_to_arcgis.py
  workflow_dispatch:       # Optional manual trigger

jobs:
  update-gpkg:
    if: |
      github.event.schedule == '30 4 * * *' ||
      github.event.schedule == '30 11 * * *' ||
      github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run update_gpkg_from_drive.py
        env:
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}
        run: |
          echo "$GOOGLE_APPLICATION_CREDENTIALS_JSON" > service_account.json
          python update_gpkg_from_drive.py

  push-to-arcgis:
    if: |
      github.event.schedule == '0 5 * * *' ||
      github.event.schedule == '0 12 * * *' ||
      github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run push_to_arcgis.py
        env:
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}
          ARCGIS_USERNAME: ${{ secrets.ARCGIS_USERNAME }}
          ARCGIS_PASSWORD: ${{ secrets.ARCGIS_PASSWORD }}
        run: |
          echo "$GOOGLE_APPLICATION_CREDENTIALS_JSON" > service_account.json
          python push_to_arcgis.py
