name: Run Every 12 Hours

on:
  schedule:
    - cron: '0 */12 * * *'  # Every 12 hours UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install geopandas google-api-python-client arcgis

    - name: Run script
      env:
        GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}
        ARCGIS_USERNAME: ${{ secrets.ARCGIS_USERNAME }}
        ARCGIS_PASSWORD: ${{ secrets.ARCGIS_PASSWORD }}
      run: |
        echo "$GOOGLE_APPLICATION_CREDENTIALS_JSON" > service_account.json
        export GOOGLE_APPLICATION_CREDENTIALS=service_account.json
        python update_gpkg_from_drive.py
